export const ARROW_UP = "↑";
export const ARROW_DOWN = "↓";

export type Person = {
  firstName: string;
  lastName: string;
  age: number;
  country: string;
  favoriteFood: string;
};

// Imagine this is making a network request to fetch data.
export const getData = (): Promise<Person[]> => {
  return new Promise((resolve) => {
    setTimeout(() => resolve(data), 500);
  });
};

const data: Person[] = [
  {
    firstName: "Liam",
    lastName: "Smith",
    age: 28,
    country: "USA",
    favoriteFood: "Pizza",
  },
  {
    firstName: "Olivia",
    lastName: "Johnson",
    age: 34,
    country: "Canada",
    favoriteFood: "Sushi",
  },
  {
    firstName: "Noah",
    lastName: "Williams",
    age: 22,
    country: "UK",
    favoriteFood: "Burger",
  },
  {
    firstName: "Emma",
    lastName: "Brown",
    age: 31,
    country: "Australia",
    favoriteFood: "Salad",
  },
  {
    firstName: "Oliver",
    lastName: "Jones",
    age: 29,
    country: "New Zealand",
    favoriteFood: "Pasta",
  },
  {
    firstName: "Ava",
    lastName: "Garcia",
    age: 27,
    country: "USA",
    favoriteFood: "Steak",
  },
  {
    firstName: "Elijah",
    lastName: "Martinez",
    age: 40,
    country: "Spain",
    favoriteFood: "Paella",
  },
  {
    firstName: "Sophia",
    lastName: "Rodriguez",
    age: 21,
    country: "Mexico",
    favoriteFood: "Tacos",
  },
  {
    firstName: "William",
    lastName: "Davis",
    age: 35,
    country: "USA",
    favoriteFood: "Ribs",
  },
  {
    firstName: "Isabella",
    lastName: "Lopez",
    age: 30,
    country: "Argentina",
    favoriteFood: "Empanadas",
  },
  {
    firstName: "James",
    lastName: "Gonzalez",
    age: 26,
    country: "Chile",
    favoriteFood: "Ceviche",
  },
  {
    firstName: "Mia",
    lastName: "Anderson",
    age: 42,
    country: "South Africa",
    favoriteFood: "Biltong",
  },
  {
    firstName: "Benjamin",
    lastName: "Thomas",
    age: 33,
    country: "USA",
    favoriteFood: "Hot Dogs",
  },
  {
    firstName: "Charlotte",
    lastName: "Taylor",
    age: 24,
    country: "UK",
    favoriteFood: "Fish and Chips",
  },
  {
    firstName: "Lucas",
    lastName: "Hernandez",
    age: 36,
    country: "France",
    favoriteFood: "Croissant",
  },
  {
    firstName: "Amelia",
    lastName: "Moore",
    age: 25,
    country: "Italy",
    favoriteFood: "Gelato",
  },
  {
    firstName: "Mason",
    lastName: "Martin",
    age: 38,
    country: "USA",
    favoriteFood: "Sandwich",
  },
  {
    firstName: "Harper",
    lastName: "Jackson",
    age: 29,
    country: "Canada",
    favoriteFood: "Poutine",
  },
  {
    firstName: "Ethan",
    lastName: "Thompson",
    age: 32,
    country: "Australia",
    favoriteFood: "Vegemite",
  },
  {
    firstName: "Abigail",
    lastName: "White",
    age: 27,
    country: "Ireland",
    favoriteFood: "Stew",
  },
  {
    firstName: "Alexander",
    lastName: "Harris",
    age: 31,
    country: "USA",
    favoriteFood: "Fried Chicken",
  },
  {
    firstName: "Sofia",
    lastName: "Clark",
    age: 23,
    country: "Brazil",
    favoriteFood: "Feijoada",
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    age: 39,
    country: "USA",
    favoriteFood: "BBQ",
  },
  {
    firstName: "Ella",
    lastName: "Robinson",
    age: 28,
    country: "Germany",
    favoriteFood: "Bratwurst",
  },
  {
    firstName: "Matthew",
    lastName: "Walker",
    age: 26,
    country: "USA",
    favoriteFood: "Mac 'n' Cheese",
  },
  {
    firstName: "Avery",
    lastName: "Young",
    age: 30,
    country: "Japan",
    favoriteFood: "Ramen",
  },
  {
    firstName: "Aiden",
    lastName: "Allen",
    age: 37,
    country: "Netherlands",
    favoriteFood: "Stroopwafel",
  },
  {
    firstName: "Scarlett",
    lastName: "King",
    age: 34,
    country: "USA",
    favoriteFood: "Apple Pie",
  },
  {
    firstName: "Joseph",
    lastName: "Wright",
    age: 22,
    country: "Italy",
    favoriteFood: "Pizza",
  },
  {
    firstName: "Grace",
    lastName: "Scott",
    age: 25,
    country: "UK",
    favoriteFood: "Shepherd's Pie",
  },
  {
    firstName: "Samuel",
    lastName: "Green",
    age: 41,
    country: "USA",
    favoriteFood: "Clam Chowder",
  },
  {
    firstName: "Chloe",
    lastName: "Baker",
    age: 21,
    country: "France",
    favoriteFood: "Baguette",
  },
  {
    firstName: "David",
    lastName: "Adams",
    age: 33,
    country: "USA",
    favoriteFood: "Fried Shrimp",
  },
  {
    firstName: "Zoey",
    lastName: "Nelson",
    age: 28,
    country: "Australia",
    favoriteFood: "Pavlova",
  },
  {
    firstName: "Carter",
    lastName: "Hill",
    age: 29,
    country: "USA",
    favoriteFood: "Cornbread",
  },
  {
    firstName: "Riley",
    lastName: "Ramirez",
    age: 24,
    country: "Spain",
    favoriteFood: "Tapas",
  },
  {
    firstName: "John",
    lastName: "Campbell",
    age: 38,
    country: "USA",
    favoriteFood: "Chili",
  },
  {
    firstName: "Lily",
    lastName: "Mitchell",
    age: 35,
    country: "UK",
    favoriteFood: "Curry",
  },
  {
    firstName: "Luke",
    lastName: "Perez",
    age: 32,
    country: "Mexico",
    favoriteFood: "Enchiladas",
  },
  {
    firstName: "Hannah",
    lastName: "Roberts",
    age: 27,
    country: "USA",
    favoriteFood: "Pancakes",
  },
  {
    firstName: "Gabriel",
    lastName: "Turner",
    age: 31,
    country: "Italy",
    favoriteFood: "Risotto",
  },
  {
    firstName: "Aria",
    lastName: "Phillips",
    age: 26,
    country: "Japan",
    favoriteFood: "Sashimi",
  },
  {
    firstName: "Henry",
    lastName: "Parker",
    age: 40,
    country: "USA",
    favoriteFood: "Gumbo",
  },
  {
    firstName: "Ella",
    lastName: "Evans",
    age: 36,
    country: "Greece",
    favoriteFood: "Moussaka",
  },
  {
    firstName: "Sebastian",
    lastName: "Edwards",
    age: 23,
    country: "USA",
    favoriteFood: "Burgers",
  },
  {
    firstName: "Zoe",
    lastName: "Collins",
    age: 34,
    country: "USA",
    favoriteFood: "Cobb Salad",
  },
  {
    firstName: "Jack",
    lastName: "Stewart",
    age: 39,
    country: "Australia",
    favoriteFood: "Meat Pie",
  },
  {
    firstName: "Natalie",
    lastName: "Sanchez",
    age: 28,
    country: "Argentina",
    favoriteFood: "Choripán",
  },
  {
    firstName: "Owen",
    lastName: "Morris",
    age: 30,
    country: "USA",
    favoriteFood: "Cheesecake",
  },
  {
    firstName: "Aubrey",
    lastName: "Rogers",
    age: 25,
    country: "France",
    favoriteFood: "Quiche",
  },
  {
    firstName: "Julian",
    lastName: "Reed",
    age: 32,
    country: "UK",
    favoriteFood: "Bangers and Mash",
  },
  {
    firstName: "Addison",
    lastName: "Cook",
    age: 27,
    country: "Canada",
    favoriteFood: "Maple Syrup",
  },
];
